server:
  port: 8763
spring:
  application:
    name: customer
eureka:
  environment: dev
  instance:
    appname: cloud customer
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
